ryu/kurama/urls.py
from django.conf.urls import patterns, url
from kurama import views

urlpatterns = patterns('',
            url(r'^$', views.index, name='index'),
            url(r'^(?P<task_id>\w{35,})/$', views.detail, name='detail'),
            url(r'^(?P<task_list>\d{2}-\w{2}&\w{2,3})/$', views.task_list, name='task_list'),
            url(r'^tag/(?P<tag>#\w+#|\$\w+\$|\*\w+\*|=|"\w+")/$', views.tag, name='tag'),
            url(r'^tagname/(?P<tagname>[\w\ ]+)/$', views.tagname, name='tagname'),
            url(r'^stats/$', views.stats, name='stats'),
            url(r'^stats/(?P<time_range>\w+)/$', views.stats, name='stats'),
            url(r'^about/$', views.about, name='about'),
            url(r'^current_week/$', views.current_week, name='current_week'),
            url(r'^populate/$', views.populate, name='populate'),
            url(r'^graph/$', views.graph, name='graph'),
            )

ryu/ryu/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'kurama.views.index', name='ryu'),
    url(r'^kurama/', include('kurama.urls', namespace="kurama")),
    url(r'^admin/', include(admin.site.urls)),
)

ryu/kurama/models.py
import datetime
from django.db import models

class TaskList(models.Model):
    """ Task List model """
    task_list_id = models.CharField(max_length=100)
    title = models.CharField(max_length=50, primary_key=True)
    info = models.CharField(max_length=1000, null=True, blank=True)
    updated = models.DateTimeField('last modification time')
    self_link = models.URLField('tasks list url')

    def __unicode__(self):
        return self.title

    def updated_on(self):
        return self.updated.strftime('%Y-%m-%d %H:%M:%S')

    class Meta:
        """ Metadata for TaskList model fields """
        # Sort ascending by title field
        ordering = ['title']
        # When using latest() return latest by completed field
        get_latest_by = ['-updated']

class Task(models.Model):
    """ Task model """
    task_list = models.ForeignKey(TaskList)
    task_id = models.CharField(max_length=100, primary_key=True)
    tag = models.CharField(max_length=20, null=True, blank=True)
    tag_name = models.CharField(max_length=40, null=True, blank=True)
    title = models.CharField(max_length=200)
    updated = models.DateTimeField('last modification time')
    self_link = models.URLField('task url')
    parent = models.CharField(max_length=100, null=True, blank=True)
    position = models.BigIntegerField()
    notes = models.CharField(max_length=1000, null=True, blank=True)
    status = models.CharField(max_length=15)
    due = models.DateTimeField('task due', null=True, blank=True)
    completed = models.DateTimeField('completed on')

    def __unicode__(self):
        return self.title

    class Meta:
        """ Metadata for Task model fields """
        # Sort descending "-" by completed field
        ordering = ['-completed']
        # When using latest() return latest by completed field
        get_latest_by = 'completed'
        order_with_respect_to = 'task_list'

class Project(models.Model):
    """ Project model """
    tag = models.CharField(max_length=10)
    name = models.CharField(max_length=30, primary_key=True)
    position = models.BigIntegerField()
    description = models.CharField(max_length=1000, null=True, blank=True)
    status = models.CharField(max_length=15)
    due = models.DateTimeField('task due', null=True, blank=True)
    completed = models.DateTimeField('completed on', null=True, blank=True)
    def __unicode__(self):
        return self.name + " tag: " + self.tag

    class Meta:
        """ Metadata for Project model fields """
        # Sort same as postions in gtasks
        ordering = ['position']

ryu/kurama/views.py
from datetime import date, timedelta
from itertools import chain
from operator import attrgetter, itemgetter
from utils import get_date_range, calc_pie_chart_data
from django.http import Http404
from django.shortcuts import render, get_object_or_404, get_list_or_404, render_to_response
from django.core.management import call_command
from kurama.models import TaskList, Task, Project

def index(request):
    """ Get latest Important and Not important tasks chain and sort querysets
    and return render response """

    latest_imds = get_list_or_404(Task.objects.order_by('-completed'),
                                  task_list="01-Im&Ds")[:5]
    latest_imnds = get_list_or_404(Task.objects.order_by('-completed'),
                                   task_list="02-Im&Nds")[:5]
    latest_im = sorted(chain(latest_imds, latest_imnds),
                       key=attrgetter('completed'),
                       reverse=True)[:5]

    latest_nids = get_list_or_404(Task.objects.order_by('-completed'),
                                  task_list="03-Ni&Ds")[:5]
    latest_ninds = get_list_or_404(Task.objects.order_by('-completed'),
                                   task_list="04-Ni&Nds")[:5]
    latest_ni = sorted(chain(latest_nids, latest_ninds),
                       key=attrgetter('completed'), 
                       reverse=True)[:5]

    tasklists = get_list_or_404(TaskList.objects.all())

    # TODO Implement in models.py Task, function for returning popular projects
    projects = get_list_or_404(Project)
    numb_of_task_per_project = {}
    for proj in projects:
        count = Task.objects.filter(tag_name=proj.name,
                                    task_list__title__contains="Im").count()
        numb_of_task_per_project[proj.name] = count
    # popular projects by number of completed tasks
    popular_projects = []
    popular_projects = sorted(numb_of_task_per_project.items(),
                              key=itemgetter(1),
                              reverse=True)[:10]

    projects = [x[0] for x in popular_projects]

    context = {'latest_im_tasks': latest_im,
               'latest_ni_tasks': latest_ni,
               'tasklists': tasklists,
               'projects': projects}

    return render(request, 'kurama/index.html', context)

def detail(request, task_id):
    task = get_object_or_404(Task, task_id=task_id)
    return render(request, 'kurama/detail.html', {'task': task})

def task_list(request, task_list):
    tasks = get_list_or_404(Task, task_list=task_list)
    context = {'task_list': task_list,
               'tasks': tasks}
    return render(request, 'kurama/task_list.html', context)

def tag(request, tag):
    tasks = get_list_or_404(Task, tag=tag)
    context = {'tag': tag,
               'tasks': tasks}
    return render(request, 'kurama/tag.html', context)

def tagname(request, tagname):
    tasks = get_list_or_404(Task, tag_name=tagname)
    context = {'tag': tagname,
               'tasks': tasks}
    return render(request, 'kurama/tag.html', context)

def stats(request, time_range=None):

    if time_range is not None:
        time_range = time_range
    elif request.GET.get('time_range'):
        time_range = request.GET.get('time_range', 'thisweek')

    tl_title = request.GET.get('tl', 'all') 
    tag = request.GET.get('tag', 'all')

    if request.GET.get('start_date') and request.GET.get('end_date'):
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')
    else:
        start_date, end_date = get_date_range(time_range)

    if tl_title == "all" and tag == "all":
        tasks = Task.objects.filter(completed__range=[start_date, end_date])
    elif tl_title == "all":
        tasks = Task.objects.filter(completed__range=[start_date, end_date],
                                    tag__icontains=tag)
    elif tag == "all":
        tasks = Task.objects.filter(completed__range=[start_date, end_date],
                                    task_list__title__icontains=tl_title)
    else:
        tasks = Task.objects.filter(completed__range=[start_date, end_date],
                                    task_list__title__icontains=tl_title,
                                    tag__icontains=tag)

    query_info = {'time_range': time_range,
                  'start_date': start_date,
                  'end_date': end_date,
                  'task_lists': tl_title,
                  'tag': tag}

    pie_chart_data = calc_pie_chart_data(tasks) 

    data = {'tasks': tasks,
            'query_info': query_info,
            'pie_chart_data': pie_chart_data}


    return render(request, 'kurama/stats.html', data)

def about(request):
    return render(request, 'kurama/about.html')

def graph(request):
    """
    pieChart example
    """
    projects = Project.objects.all()
    numb_of_task_per_project = {}
    for proj in projects:
        count = Task.objects.filter(tag_name=proj.name,
                                    task_list__title__contains="Im").count()
        numb_of_task_per_project[proj.name] = count
    # popular projects by number of completed tasks
    popular_projects = []
    popular_projects = sorted(numb_of_task_per_project.items(),
                              key=itemgetter(1),
                              reverse=True)[:10]

    xdata = [x[0] for x in popular_projects]
    ydata = [x[1] for x in popular_projects]

    color_list = ['#5d8aa8', '#e32636', '#efdecd', '#ffbf00', '#ff033e',
                  '#a4c639', '#b2beb5', '#8db600', '#7fffd4', '#ff007f',
                  '#ff55a3', '#5f9ea0']
    extra_serie = {
        "tooltip": {"y_start": "", "y_end": " tasks"},
        "color_list": color_list
    }
    chartdata = {'x': xdata, 'y1': ydata, 'extra1': extra_serie}
    charttype = "pieChart"
    chartcontainer = 'piechart_container'  # container name

    data = {
        'charttype': charttype,
        'chartdata': chartdata,
        'chartcontainer': chartcontainer,
        'extra': {
            'x_is_date': False,
            'x_axis_format': '',
            'tag_script_js': True,
            'jquery_on_ready': False,
        }
    }

    return render_to_response('kurama/graph.html', data)

def current_week(request):
    # get tasks from current week, week starts from saturday
    today = date.today()
    # offset/delta from current week day till saturday,
    # "last saturday" can't be same as "today"
    offset = (today.weekday() + 1) % 7 + 1
    last_saturday = today - timedelta(days=offset)
    current_week = Task.objects.filter(completed__range=[last_saturday, today])
    date_range = {'start_date': last_saturday, 'end_date': today}
    return render(request, 'kurama/current_week.html', {'tasks': current_week,
                                                 'date_range': date_range})

def populate(request):
    # TODO write date range logic
    call_command('populate_db', 'kurama', interactive=False)
    return render(request, 'kurama/populate.html')

ryu/kurama/templates/kurama/about.html
{# vim:set et sw=2 ts=2 sts=2 tw=120: #}
{% extends "base.html" %}

{% block content %}

<div class="page-header">
  <br>
  <h2>Ryu - Project for devloping app for analysis and evaluation of 
    time management system</h2>
</div>

<h3>Why Ryu?</h3>
<p class="lead">
<strong>Ryu</strong> is a Japanese dragon with three claws! And I'm gonna slay
that dragon! Haha. Essentially it's my attempt at going against my fear of
thinking that I can't be good programmer. Also this project is about time
management (croat. raspolaganje vremenom) so that's why I'm making app Kurama
that will slay project Ryu :-) 
</p>

{% endblock content %}

ryu/kurama/templates/kurama/current_week.html
{# vim:set et sw=2 ts=2 sts=2 tw=120: #}
{% extends "base.html" %}

{% block content %}

<div class="page-header">
  <br>
  <h1>List of tasks from {{ date_range.start_date }} to {{ date_range.end_date }} </h1>
</div>

{% if tasks %}
<ul class="list-group">
  {% for task in tasks %}
  <li class="list-group-item> {{ task.title }}</li>
  {% endfor %}
</ul>
{% else %}
<p>No tasks are available.</p>
{% endif %}
{% endblock content %}

ryu/kurama/templates/kurama/detail.html
{# vim:set et sw=2 ts=2 sts=2 tw=120: #}
{% extends "base.html" %}

{% block content %}

<div class="page-header">
  <br>
  <h1>Task details</h1>
</div>

<div class="col-md-8">
  {% if task %}
  <ul class="list-group">
    <li class="list-group-item active">
    <h4 class="list-group-item-heading">{{ task.title }}</h4> </li>
    <li class="list-group-item">List: {{ task.task_list }} </li>
    <li class="list-group-item">Tag: {{ task.tag }} </li>
    <li class="list-group-item">List: {{ task.task_list }} </li>
    <li class="list-group-item">Tag: {{ task.tag }} - {{ task.tag_name }} </li>
    <li class="list-group-item">Updated: {{ task.updated }} </li>
    <li class="list-group-item">Notes: {{ task.notes|linebreaks}} </li>
    <li class="list-group-item">Status: {{ task.status }} </li>
    <li class="list-group-item">Due: {{ task.due }} </li>
    <li class="list-group-item">Completed: {{ task.completed }} </li>
  </ul>
  {% else %}
  <p>No task are available.</p>
  {% endif %}
</div>

{% endblock content %}

ryu/kurama/templates/kurama/graph.html
{# vim:set et sw=2 ts=2 sts=2 tw=120: #}
{% extends "base.html" %}
{% load nvd3_tags %}

{% block extrahead %}

{% include_chart_jscss %}
{% load_chart charttype chartdata chartcontainer extra %}

{% endblock extrahead %}


{% block content %}

<div class="page-header">
  <br>
  <h1>Piechart presenting number of tasks per project/tag</h1>
  <h2>Filterd by important task lists from 2014-01-01 - until last update</h2>
</div>

{% include_container chartcontainer 600 800 %}

{% endblock content %}

ryu/kurama/templates/kurama/index.html
{# vim:set et sw=2 ts=2 sts=2 tw=120: #}
{% extends "base.html" %}

{% block content %}

<div class="page-header">
  <br>
  <h1>Latest completed tasks</h1>
</div>

<div class="row">
  <div class="col-sm-4">
    {% if latest_im_tasks %}
    <ul class="list-group">
      <li class="list-group-item active">
      <h4 class="list-group-item-heading">Important Tasks</h4>
      </li>
      {% for task in latest_im_tasks %}
      <li class="list-group-item"><a href="{% url 'kurama:detail' task.task_id %}">{{ task.task_list}} - {{ task.title }}</a></li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No tasks are available.</p>
    {% endif %}
  </div>
  <div class="col-sm-4">
    {% if latest_ni_tasks %}
    <li class="list-group-item active">
    <h4 class="list-group-item-heading">Not Important Tasks</h4>
    </li>
    <ul class="list-group">
      {% for task in latest_ni_tasks %}
      <li class="list-group-item"><a href="{% url 'kurama:detail' task.task_id %}">{{ task.task_list}} - {{ task.title }}</a></li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No tasks are available.</p>
    {% endif %}
  </div>
  <div class="col-sm-4">
    {% if tasklists %}
    <ul class="list-group">
      <li class="list-group-item active">
      <h4 class="list-group-item-heading">Tasks lists</h4>
      </li>
      {% for tl in tasklists %}
      <li class="list-group-item">
      <h5 class="list-group-item-heading">
        <a href="{% url 'kurama:task_list' tl.title %}">{{ tl.title }}</a>
        <p class="list-group-item-text"> {{ tl.info }}</p>
      </h5>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No task lists are available </p>
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <ul class="list-group">
      <li class="list-group-item active">
      <h4 class="list-group-item-heading">Statistcs by</h4>
      <li class="list-group-item"><a href="{% url 'kurama:stats' %}">Global stats</a></li>
      <li class="list-group-item"><a href="{% url 'kurama:current_week' %}">Current week</a></li>
    </ul>
  </div>
  <div class="col-sm-4">
    {% if projects %}
    <ul class="list-group">
      <li class="list-group-item active">
      <h4 class="list-group-item-heading">Popular projects/task group</h4>
      </li>
      {% for proj in projects %}
      <li class="list-group-item">
      <a href="{% url 'kurama:tagname' proj %}">{{ proj }}</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No projects are available </p>
    {% endif %}
  </div>
</div>

{% endblock content %}

ryu/kurama/templates/kurama/populate.html
{# vim:set et sw=2 ts=2 sts=2 tw=120: #}
{% extends "base.html" %}

{% block content %}
<div class="page-header">
  <br>
  <h1>JEAY</h1>
</div>

{% endblock content %}

ryu/kurama/templates/kurama/stats.html
{# vim:set et sw=2 ts=2 sts=2 tw=120: #}
{% extends "base.html" %}
{% load nvd3_tags %}

{% block extrahead %}
{% include_chart_jscss %}

{% endblock extrahead %}

{% block content %}

<div class="page-header">
  <br>
  <h1> Statistical analysis page </h1>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Filter</h3>
  </div>
  <form action="/kurama/stats/" method="get" accept-charset="utf-8">
  <div class="panel-body">
    <div class="row">
      <div class='col-sm-4'>
          <div class="form-group">
            <label for="tasklist">Task list</label>
            <select class="form-control" id="tasklist" name="tl">
              <option>all</option>
              <option>Im</option>
              <option>Ni</option>
              <option>Im&amp;Ds</option>
              <option>Im&amp;Nds</option>
              <option>Ni&amp;Ds</option>
              <option>Ni&amp;Nds</option>
            </select>
          </div>
      </div> <div class='col-sm-4'>
          <div class="form-group">
            <label for="tag">Tag/Project</label>
            <div class='input-group' id='tag'>
              <input type='text' class="form-control" name="tag" value="all" />
              <span class="input-group-addon"><span class="glyphicon glyphicon-list"></span>
              </span>
            </div>
          </div>
      </div>
      <div class='col-sm-4'>
          <div class="form-group">
            <label for="time-range">Time range</label>
            <select class="form-control" name="time_range">
              <option>thisweek</option>
              <option>thismonth</option>
              <option>lastweek</option>
              <option>lastmonth</option>
              <option>thisquarter</option>
            </select>
          </div>
      </div>
    </div>
    <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <label for="startdatetimepicker">Start date</label>
            <div class='input-group date' id='startdatetimepicker'>
              <input type='text' class="form-control" data-date-format="YYYY-MM-DD" name="start_date" />
              <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <label for="enddatetimepicker">End date</label>
            <div class='input-group date' id='enddatetimepicker'>
              <input type='text' class="form-control" data-date-format="YYYY-MM-DD" name="end_date" value="" />
              <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>
    </div>
      <div class="row">
        <div class="col-sm-4">
          <button type="submit" class="btn btn-default">Submit</button>
        </div>
      </div>
      <script type="text/javascript">
        $(function () {
            $('#startdatetimepicker').datetimepicker({
              pickTime:false
            });
            $('#enddatetimepicker').datetimepicker({
              pickTime:false
            });
            $("#startdatetimepicker").on("dp.change",function (e) {
               $('#enddatetimepicker').data("DateTimePicker").setMinDate(e.date);
            });
            $("#enddatetimepicker").on("dp.change",function (e) {
               $('#startdatetimepicker').data("DateTimePicker").setMaxDate(e.date);
            });
        });
      </script>
  </div>
  </form>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Query Info</h3>
  </div>
  <div class="panel-body">
    List of tasks from {{ query_info.start_date }} to {{ query_info.end_date }}
    {% if query_info.task_lists == "all" %}
    from all task lists and
    {% else %}
    for task list with name {{ query_info.task_lists }} and
    {% endif %}
    {% if query_info.tag == "all" %}
    for all projects
    {% else %}
    for projects with name {{ query_info.tag }}
    {% endif %}
  </div>
</div>

<div id="content">
  <ul class="nav nav-tabs">
    <li role="presentation" class="active"><a class="tasks" href="#tasks" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> Tasks</a></li>
    <li role="presentation"><a class="graphs" href="#graphs" data-toggle="tab"><i class="glyphicon glyphicon-stats"></i> Graphs</a></li>
    <li role="presentation"><a class="analysis" href="#analysis" data-toggle="tab"><i class="glyphicon glyphicon-retweet"></i> Analysis</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tasks">
      <h3>Task list </h3>
      <div class="col-md-12" >
        <table class="table table-hover">
        {% if tasks %}
          <tr><td>Task list</td><td>Project</td><td>Task title</td></tr>
          {% for task in tasks|dictsortreversed:"completed" %}
          <tr>
            <td><a href="{% url 'kurama:task_list' task.task_list.title %}"> {{ task.task_list.title }}</a></td>
            <td><a href="{% url 'kurama:tag' task.tag %}"> {{ task.tag }}</a></td>
            <td><a href="{% url 'kurama:detail' task.task_id %}"> {{ task.title }}</a></td>
          </tr>
          {% endfor %}
        {% else %}
          <tr><td>No tasks are available</td></tr>
        {% endif %}
        </table>
      </div>
    </div>
    <div class="tab-pane" id="graphs">
      <h3>Graphssss</h3>
        <div class="col-md-12">
          {% include_container pie_chart_data.chartcontainer 600 800 %}
        </div>
    </div>
    <div class="tab-pane" id="analysis">
      <h3>Analysis </h3>
      <p>Analysis Analysis Analysis </p>
    </div>
<script>
  $(".graphs").click(function() {
      {% load_chart pie_chart_data.charttype pie_chart_data.chartdata pie_chart_data.chartcontainer pie_chart_data.extra %}
  });
</script>
  </div>
</div> 
{% endblock content %}

ryu/kurama/templates/kurama/tag.html
{# vim:set et sw=2 ts=2 sts=2 tw=120: #}
{% extends "base.html" %}

{% block content %}

<div class="page-header">
  <br>
  <h1>Complete list of tasks from tag: {{ tag }}</h1>
</div>

{% if tasks %}
<ul class="list-group">
  {% for task in tasks %}
  <li class="list-group-item">  
  <a href="{% url 'kurama:detail' task.task_id %}">{{ task.title }}</a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No tasks are available.</p>
{% endif %}
{% endblock content %}

ryu/kurama/templates/kurama/task_list.html
{# vim:set et sw=2 ts=2 sts=2 tw=120: #}
{% extends "base.html" %}

{% block content %}

<div class="page-header">
  <br>
  <h1>Complete list of tasks from {{ task_list }}</h1>
</div>

{% if tasks %}
<ul class="list-group">
  {% for task in tasks %}
  <li class="list-group-item> {{ task.title }}</li>
  {% endfor %}
</ul>
{% else %}
<p>No tasks are available.</p>
{% endif %}
{% endblock content %}