ryu/kurama/urls.py
from django.conf.urls import patterns, url
from kurama import views

urlpatterns = patterns('',
            url(r'^$', views.index, name='index'),
            url(r'^(?P<task_id>\w{35,})/$', views.detail, name='detail'),
            url(r'^(?P<task_list>\d{2}-\w{2}&\w{2,3})/$', views.task_list, name='task_list'),
            url(r'^tag/(?P<tag>#\w+#|\$\w+\$|\*\w+\*|=|"\w+")/$', views.tag, name='tag'),
            url(r'^tagname/(?P<tagname>[\w\ ]+)/$', views.tagname, name='tagname'),
            url(r'^stats/$', views.stats, name='stats'),
            url(r'^stats/(?P<time_range>\w+)/$', views.stats, name='stats'),
            url(r'^about/$', views.about, name='about'),
            url(r'^current_week/$', views.current_week, name='current_week'),
            url(r'^populate/$', views.populate, name='populate'),
            url(r'^graph/$', views.graph, name='graph'),
            )

ryu/ryu/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'kurama.views.index', name='ryu'),
    url(r'^kurama/', include('kurama.urls', namespace="kurama")),
    url(r'^admin/', include(admin.site.urls)),
)

ryu/templates/base.html
{# vim:set et sw=2 ts=2 sts=2 tw=120: #}
{% load staticfiles %}<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0
Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Language" content="en-us" />
<title>{% block title %}Kurama - The Time Management Statistcs App{% endblock %} </title>
<meta name="ROBOTS" content="ALL" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="MSSmartTagsPreventParsing" content="true" />
<meta name="Copyright" content="Marijan Svalina" />
<meta name="keywords" content="Time-Management, Python, Django" />
<meta name="description" content="Kurama is app for statistcal analysis of completed tasks that will help with
evaulations and retrospectives of completed work." />

<script type="text/javascript" src="/static/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="/static/moment/min/moment.min.js"></script>
<script type="text/javascript" src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="/static/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />

{# Load the tag libraries #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block extrahead %} {% endblock extrahead %}

</head>

<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'ryu' %}">Slaying Ryu</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'kurama:index' %}">Kurama</a></li>
        <li><a href="{% url 'kurama:stats' %}">Stats</a></li>
        <li><a href="{% url 'kurama:about' %}">About</a></li>
        <li><a href="{% url 'kurama:populate' %}">Update</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class="container theme-showcase" role="main">
  {% block content %}{% endblock content %}
</div><!-- /.container -->

</body>
</html>